// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a sql migration is added or changed.
    // this is only useful if you have a persistent database.
    // We currently don't have a persistent database, so we don't need this.
    // println!("cargo:rerun-if-changed=grafton-server/migrations");
}
